name: CI/CD Frontend FLCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build Angular
        working-directory: ./frontend-flcs 
        run: |
          npm install
          # Le --no-prerender évite les erreurs sur les routes :id
          npm run build -- --configuration production --no-prerender

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Avec Angular 21, les fichiers sont dans dist/frontend-flcs/browser
          source: "frontend-flcs/dist/frontend-flcs/browser/**"
          target: "/var/www/frontend/public"
          # strip_components: 4 permet de ne copier que le CONTENU de 'browser'
          strip_components: 4

      - name: Nettoyage Post-Déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Optionnel : s'assurer que les permissions sont bonnes pour Nginx
            chown -R www-data:www-data /var/www/frontend/public
            chmod -R 755 /var/www/frontend/public