name: CI/CD Frontend FLCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # CETTE ÉTAPE FORCE L'URL HTTPS DANS LE CODE AVANT LE BUILD
      - name: Force Production API URL
        working-directory: ./frontend-flcs
        run: |
          sed -i 's|http://localhost:8080/api|https://flcs-center.com/api|g' src/environments/environment.ts
          sed -i 's|http://localhost:8080/api|https://flcs-center.com/api|g' src/environments/environment.prod.ts

      - name: Build Angular
        working-directory: ./frontend-flcs 
        run: |
          npm install
          npm run build -- --configuration production --no-prerender

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend-flcs/dist/frontend-flcs/browser/**"
          target: "/var/www/frontend/public"
          strip_components: 4

      - name: Nettoyage Post-Déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chown -R www-data:www-data /var/www/frontend/public
            chmod -R 755 /var/www/frontend/public